// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3S0tlANMFhS8Bz_eExClmk_rHCAn7aGc',
    appId: '1:46001575925:web:2ea0207f6da0d66f1172bc',
    messagingSenderId: '46001575925',
    projectId: 'adu-pass',
    authDomain: 'adu-pass.firebaseapp.com',
    storageBucket: 'adu-pass.firebasestorage.app',
    measurementId: 'G-8KTE5M05T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGs3OQUnFQBq5XfL6329YIpKjWXUFzOA',
    appId: '1:46001575925:android:ed16537583c1e9cb1172bc',
    messagingSenderId: '46001575925',
    projectId: 'adu-pass',
    storageBucket: 'adu-pass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZb5KNx9qYjlR26Lvow4g7xAotLiLk7IM',
    appId: '1:46001575925:ios:337159bbd636dffa1172bc',
    messagingSenderId: '46001575925',
    projectId: 'adu-pass',
    storageBucket: 'adu-pass.firebasestorage.app',
    iosBundleId: 'com.melikan.altgate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZb5KNx9qYjlR26Lvow4g7xAotLiLk7IM',
    appId: '1:46001575925:ios:337159bbd636dffa1172bc',
    messagingSenderId: '46001575925',
    projectId: 'adu-pass',
    storageBucket: 'adu-pass.firebasestorage.app',
    iosBundleId: 'com.melikan.altgate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3S0tlANMFhS8Bz_eExClmk_rHCAn7aGc',
    appId: '1:46001575925:web:4d3068982cd805961172bc',
    messagingSenderId: '46001575925',
    projectId: 'adu-pass',
    authDomain: 'adu-pass.firebaseapp.com',
    storageBucket: 'adu-pass.firebasestorage.app',
    measurementId: 'G-CCYRRQY3T6',
  );
}
